### PR TITLE
Expire only unused dynamic routes instead of flushing all of them

### PR DESCRIPTION
**Pull request by gromit1811**

### CODE REVIEW

**Comment by troglobit** [comment]
Awesome patch(es), as usual I might add! :smiley: :+1: 

Was hoping I to merge my own patch queue (incl. huge refactor of `select()` to a home-brew mini-event loop, and relocation of all source files to an `src/` subdirectory). 

*Would you mind terribly if I postpone this PR until I've merged that refactor?*

As compensation I'm offering to hand-merge your fixes in the hope you could perhaps test the end result ... :worried:

**Comment by troglobit** [comment]
There, took a while to finalize the changes in my own patch queue, but now I've hand-merged your PR as well.  I really hope I got your timer interval fixes right with the new model.

If you could have a quick look at the resulting code I'd be most grateful! :pray: 

Just FYI, I intend to continue working on cleaning up the code, in particular the timer handling since I have a patch for [RFC4286](https://tools.ietf.org/html/rfc4286) coming up soon.  It's based on my [mrdisc](https://github.com/troglobit/mrdisc) prototype, which also need an interval timer (and more sockets).  Ideally I'd like to get the timers more in line with what I did with the socket callbacks.

**Comment by gromit1811** [comment]
Great, looks good to me and a quick test confirms it's working as intended.

BTW, regarding timer handling: I wanted to do a patch that replaces
gettimeofday() with clock_gettime(CLOCK_MONOTONIC) (where available) to
become independent of clock adjustments for a long time. Right now, if
somebody sets the clock backwards, our timers stop working. But it's not
done yet and I probably lack the autoconf-fu to check whether
clock_gettime() is available, so I'll wait for your further cleanup first.

I've got another patch to rebase and send in the meantime ;-)

**Comment by troglobit** [comment]
Great, thank you for checking! :)

Yeah, I've been thinking about `gettimeofday()` and all it's little issues, thanks for reminding me.
**\*updates TODO\***

Looking forward to it! :-)

**Comment by troglobit** [comment]
@gromit1811 I've just pushed [support for monotonic timers](https://github.com/troglobit/smcroute/commit/63bcaaf01e642fb56b5dadcffd0b2b63dd6d9739) to master.  If you have time to audit it I'd be most grateful. I've verified that the cache timeout handling still works, but more eyes on the code is always better.

The overhead for that single timer looks a bit ridiculous atm., but there's more coming soon that will use timers.  Cheers :)

**Comment by gromit1811** [comment]
Wow, big changes. I'm not at all familiar with timer_create(), so I probably won't notice subtle issues with that. In general, it looks good to me, but of course, I have a few comments:
* I think expired() is wrong. Shouldn't this rather be something like this:
  ```
  diff --git a/src/timer.c b/src/timer.c
  index a1d8816..07f3976 100644
  --- a/src/timer.c
  +++ b/src/timer.c
  @@ -56,8 +56,8 @@ static void set(struct timer *t, struct timespec *now)
   
   static int expired(struct timer *t, struct timespec *now)
   {
  -       if (t->timeout.tv_sec  <= now->tv_sec &&
  -           t->timeout.tv_nsec <= now->tv_nsec)
  +       if (t->timeout.tv_sec  < now->tv_sec ||
  +           (t->timeout.tv_sec == now->tv_sec && t->timeout.tv_nsec <= now->tv_nsec))
                  return 1;
   
          return 0;
  ```
* There's a gettimeofday() left in mroute4_dyn_expire(). That should probably become clock_gettime(CLOCK_MONOTONIC, ...) as well.
* Can we rely on clock_gettime(CLOCK_MONOTONIC, ...) to be universally available? We could add a fallback to gettimeofday(), but then, if clock_gettime(CLOCK_MONOTONIC, ...) is missing, timer_create(CLOCK_MONOTONIC, ...) probably won't be there either and there's no simple fallback for that.
* For static linking, I need -lpthread in addition to -lrt. When linking dynamically, that gets pulled in automatically, but it shouldn't hurt to do this explicitly in any case (or does it need an autoconf check?).

**Comment by troglobit** [comment]
Thank you for having a look!  :smiley: 

Yeah I've had these idea about refactoring SMCRoute laying around for quite some time, and now I needed to get the mrdisc support in there for work.

- [X] Good catch with `expired()`, fixed now!
- [X] Fixed remaining `gettimeofday()` in `mroute4_dyn_expire()`
- [ ] I spent a great deal of time investigating .. time.  It seems `clock_gettime()` and `CLOCK_MONOTONIC` is available on all the main target platforms for SMCRoute: Linux, *BSD, so we should be good. I plan to test on NetBSD, FreeBSD and OpenBSD very soon, in addition to Linux (down to 3.0.101).
- [ ] Hmm, `-lpthread` usually makes me see red, but if it's only when building statically then I guess it's up to the libc how they've implemented it.  We could add a small check to configure for this.  Good of you to bring it up!

**Comment by troglobit** [comment]
OK, I've tested all new features.  Thank you again for bringing up the issue with `-lpthread` ... turns out I had overlooked the fact that `timer_settime()` requires it.  Working on some configure checks now and to test again before making the release during the weekend.

**Pull request merged**
