### PR TITLE
Remove duplicate documentation of option -c

### PR DESCRIPTION
**Pull request by gromit1811**

### CODE REVIEW

**Comment by troglobit** [comment]
Good catch, although I think the wording in the second one (removed but your patch) is better ...

**Comment by gromit1811** [comment]
More to follow regarding expiration of dynamic routes, but I need to
rebase/retest first. I think one of the pending commits also updates the
remaining description again.

Martin

**Comment by troglobit** [comment]
First of all, s/but/by/ ... obviously ...

Oooh, more pull requests coming, more neat stuff ... may I ask who the benefactors are? :smirk: 

There's been quite a few changes recently, mostly related to refactoring of `smcroutectl`.  Hope I haven't messed anything up too bad for your rebase there. For future reference, when you've got stuff queued, just drop be me a note on email/twitter in case I'm planning some weekend work :smiley:

**Comment by gromit1811** [comment]
Yes, more pull requests in the pipeline (mostly imporving handling of
dynamic routes plus one for interface name wildcards but the latter is
pretty ugly, so I'm not sure about it yet).

Just noticed that my profile page on github was pretty empty so far (I'm new
to github), so I updated it a bit. I'm using smcroute for a project at work
at the moment. Previously, I also used a hacked mrouted and a half mrouted
plus routing logic in Python on top of it, but for the current project, we
decided that something simple like smcroute should be sufficient. Well,
let's see for how long this decision survives...

The time I have to clean up our local smcroute modifications and to push them
upstream is pretty limited and difficult to plan in advance. So better don't
hold back any changes, could be that you'd have to wait for weeks until I
finally get my pull requests done.

**Comment by troglobit** [comment]
Great stuff, really looking forward to it!  Take your time, I really appreciate your work, and don't feel you have to rush it. Perfection takes time, and all that :)

 I have a few more features lined up before the next major release. I've not yet made them public, except for the upcoming [mrdisc](https://github.com/troglobit/mrdisc) support I've developed in a separate repo. But we've run into a rather annoying issue with multicast routing and 1:1 NAT in a train setup, so I'll likely also add a source-net-scoping feature before 2.3 goes out.

**Pull request merged**
