### PR TITLE
IPv6 source wildcard initial implementation

### PR DESCRIPTION
**Pull request by hubertmis**
I need an IPv6 wildcard multicast forwarding (discussed in #31) for my project very much.
I created an initial implementation. It's mostly copy-paste of IPv4 code modified to work with IPv6 addresses. Tested on a RPi router and seems to work correctly. At least I can forward site-local ICMPv6 echo :)
I'm not sure if the quality of the code is enough to pull it. I hope this PR can be a base for a more thoughtful solution.

### CODE REVIEW

**Comment by troglobit** [comment]
This is awesome! I've been meaning to add this myself, but my experience with IPv6 is still limited so it would've taken me quite some time to achieve the same thing as you've done, not to mention testing it.

Thank you so much! :smiley::+1: 

I honestly have no complaints on the code at the moment. However, before the next release I will likely end up in refactoring mode and possibly change/collapse/simplify some constructs.  Like I've recently done with `mcgroup.c`.  There was so much code duplication and unnecessary complexity that's built up over the years. 

I'm merging this, and I welcome more fixes and/or cleanup from you since you now have earned a gold star :star2:

**Comment by idosch** [comment]
Hi,

With this commit I can't seem to add IPv6 multicast routes after I deleted them. smcroute seems to think they still exist and emits the following error: "smcroutectl: Static route already exists".

To reproduce:

```
#!/bin/bash

smcroutedir="$(mktemp -d)"
id=test123

for i in $(seq 1 3); do
        ip link add name dummy$i up multicast on type dummy
        echo "phyint dummy$i enable" >> $smcroutedir/$id.conf
done

touch /var/run/$id.sock
smcrouted -N -I $id -f $smcroutedir/$id.conf \
        -P $smcroutedir/$id.pid

echo "Add multicast route"
smcroutectl -I $id add dummy1 2001:db8:1::2 ff0e::3 dummy2 dummy3
echo "Routing table:"
ip -6 mroute show

echo -e "\n\nRemove multicast route"
smcroutectl -I $id remove dummy1 2001:db8:1::2 ff0e::3 dummy2 dummy3
echo "Routing table:"
ip -6 mroute show

echo -e "\n\nTry adding multicast route again"
smcroutectl -I $id add dummy1 2001:db8:1::2 ff0e::3 dummy2 dummy3
smcroutectl -I $id remove dummy1 2001:db8:1::2 ff0e::3 dummy2 dummy3

pkill smcrouted

for i in $(seq 1 3); do
        ip link del dev dummy$i
done

rm -r $smcroutedir
```

Output with this commit:

```
# ./test.sh                                                                                                                                          
Add multicast route    
Routing table:         
(2001:db8:1::2,ff0e::3)          Iif: dummy1     Oifs: dummy2 dummy3  State: resolved 
                                                                                      
                                           
Remove multicast route                                                                
Routing table:                             
                                                                                      
                                           
Try adding multicast route again           
smcroutectl: Static route already exists   
smcroutectl: failed removing multicast route, does not exist.                         
```

Output without this commit (expected result):

```
# ./test.sh                                                      
Add multicast route                                                                   
Routing table:                             
(2001:db8:1::2,ff0e::3)          Iif: dummy1     Oifs: dummy2 dummy3  State: resolved
                                           
                                                                                      
Remove multicast route         
Routing table:                             
                                           
                                                                                      
Try adding multicast route again
```

Please let me know if more info is needed.

Thanks

**Comment by troglobit** [comment]
@idosch Awesome feedback, looks like you've found a bug!  Would you mind posting this a separate bug report instead?  This pull request is closed and it's easier for me to follow-up on open issues.

**Comment by idosch** [comment]
> @idosch Awesome feedback, looks like you've found a bug! Would you mind posting this a separate bug report instead? This pull request is closed and it's easier for me to follow-up on open issues.

Hi,

Thanks for the quick response. I have opened a new issue and referenced this pull request.

**Comment by troglobit** [comment]
@idosch Thank you!

**Pull request merged**
